import { StyleSheet, StatusBar, Platform } from "react-native";
import * as Font from "expo-font";

export const HomePage = StyleSheet.create({
  backgroundStyle: {
    flex: 1,
    backgroundColor: "#1fb4a1",
    alignItems: "center",
    paddingTop: StatusBar.currentHeight - 20,
  },
  settingsAndSelection: {
    width: "99%",
    height: "90%",
    position: "relative",
    flexDirection: "row",
    top: 35,
    borderRadius: 15,
    backgroundColor: "white",
    alignItems: "flex-start",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  selectionPanel: {
    gap: 30,
    flexDirection: "row",
    padding: 20,
    overflow: "hidden",
  },
  settingsText: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 40,
    height: 50,
    fontFamily: "Roboto",
    borderBottomColor: "lightgray",
    borderBottomWidth: 1,
    borderTopColor: "lightgray",
    borderTopWidth: 1,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  settingsSignOut: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 40,
    height: 50,
    fontFamily: "Roboto-Thin",
    borderBottomColor: "lightgray",
    borderBottomWidth: 1,
    borderTopColor: "lightgray",
    borderTopWidth: 1,
    marginTop: 240,
    borderBottomLeftRadius: 15,
  },
  settingsProfileText: {
    height: 40,
    height: 50,
    fontFamily: "Roboto-Bold",
    paddingTop: 5,
  },
  settingsPanel: {
    width: "20%",
    height: "100%",
    alignItems: "center",
    paddingTop: 50,
    gap: 20,
    borderRightColor: "lightgray",
    borderRightWidth: 1,
  },
  settingsProfile: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 20,
    height: 50,
    flexDirection: "row",
    marginBottom: 50,
    borderBottomColor: "lightgray",
    borderBottomWidth: 1,
    borderTopColor: "lightgray",
    borderTopWidth: 1,
  },
  settingsImage: {
    marginRight: 5,
    width: 40,
    height: 40,
    borderRadius: 25,
  },
  postButton: {
    position: "absolute",
    right: 20,
    bottom: 20,
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    height: 40,
    height: 50,
    borderRadius: 15,
    backgroundColor: "#1fb4a1",
    fontFamily: "Roboto",
    borderColor: "lightgray",
    borderWidth: 2,
  },
  logoImage: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  logoText: {
    fontSize: 24,
    fontFamily: "Roboto-Bold",
    color: "#1fb4a1",
    paddingTop: 3,
  },
  logoStyle: {
    flexDirection: "row",
    flex: 1,
    height: 60,
  },
});

export const PostView = StyleSheet.create({
  backgroundStyle: {
    position: "absolute",
    top: Platform.OS === "web" ? "15%" : "25%",
    left: Platform.OS === "web" ? "35%" : "12%",
    backgroundColor: "white",
    borderColor: "lightgray",
    borderWidth: 1,
    borderRadius: 15,
    width: Platform.OS === "web" ? "40%" : 300,
    height: Platform.OS === "web" ? "70%" : 400,
    paddingTop: 40,
    paddingBottom: 20,
    alignItems: "center",
    flexDirection: "column",
  },
  titleInput: {
    width: "100%",
    flex: 0.2,
    padding: 10,
    borderBottomColor: "lightgray",
    borderBottomWidth: 1,
  },
  captionInput: {
    width: "100%",
    flex: 1,
    padding: 10,
  },
  postDisplayButton: {
    flex: 0.2,
    marginTop: 10,
    fontWeight: 500,
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    borderRadius: 15,
    backgroundColor: "#1fb4a1",
    fontFamily: "Roboto",
    borderColor: "lightgray",
    borderWidth: 2,
  },
  postDropdownButton: {
    fontSize: 14,
    flex: 0.2,
    marginTop: 10,
    fontWeight: 500,
    alignItems: "center",
    marginBottom: 10,
    justifyContent: "center",
    width: 100,
    fontFamily: "Roboto",
    borderColor: "lightgray",
    borderWidth: 1,
  },
  closeButtonTouch: {
    width: "100%",
    flex: 0.1,
    borderColor: "lightgray",
    alignItems: "flex-end",
    paddingRight: 20,
  },
  closeButton: {
    width: 20,
    height: 20,
  },
});

export const PostDesign = StyleSheet.create({
  backgroundStyle: {
    width: Platform.OS === "web" ? 250 : 400,
    height: Platform.OS === "web" ? 300 : 400,
    flexDirection: "column",
    backgroundColor: Platform.OS === "web" ? "#1fb4a1" : "whitesmoke",
    borderRadius: 15,
    marginBottom: 20,
    marginRight: 10,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  imageStyle: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: Platform.OS === "web" ? 250 : 400,
    height: Platform.OS === "web" ? 150 : 200,
    resizeMode: "cover",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  textStyle: {
    flex: 1,
    flexDirection: "column",
    padding: 8,
  },
  titleStyle: {
    flex: 0.5,
    color: Platform.OS === "web" ? "white" : "black",
    fontFamily: "Roboto-Bold",
  },
  captionStyle: {
    flex: 1,
    fontFamily: "Roboto-Thin",
    color: Platform.OS === "web" ? "white" : "black",
  },
  ratingStyle: {
    flex: 0.5,
    alignSelf: "flex-end",
    fontFamily: "Roboto-Thin",
    color: Platform.OS === "web" ? "white" : "black",
  },
});

export const AndroidHomePage = StyleSheet.create({
  selectionPanel: {
    position: "relative",
    width: "100%",
    height: "100%",
    marginTop: StatusBar.currentHeight,
    padding: 20,
    flexDirection: Platform.OS === "web" ? "row" : "column",
  },
  taskBar: {
    position: "absolute",
    backgroundColor: "white",
    width: "80%",
    height: 60,
    borderRadius: 15,
    bottom: -15,
    gap: 60,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  logoBar: {
    position: "absolute",
    width: 60,
    height: 60,
    bottom: 15,
  },
  imageLogo: {
    width: 60,
    height: 60,
  },
  taskText: {
    alignItems: "center",
    justifyContent: "center",
    height: 60,
    width: 60,
    fontWeight: 800,
    fontFamily: "Roboto",
    paddingBottom: 15,
  },
});
